services:
  - type: web
    name: pixells-basic-api
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    healthCheckPath: /health
    numInstances: 1
